### ISSUE TITLE
Add compatibility to "App Icons Taskbar"

### ISSUE THREAD

**Issue by koppor** [metehan-arslan/gnome-compact-top-bar#12]
I use [App Icons Taskbar](https://gitlab.com/AndrewZaech/aztaskbar), which is not resized.

The result are cut-off icons:

![image](https://github.com/metehan-arslan/gnome-compact-top-bar/assets/1366654/856f1ad9-b835-402b-8431-beb4843a78cd)

Not sure whether there is an easy fix possible.

**Comment by metehan-arslan** [comment]
Hello Oliver,

Unfortunately I can not control 3rd party extension sizes. Can you resize the icons on extension's settings? If so you can make them fit...

...or you can alter gnome-compact-top-bar's `stylesheet.css`under `~/.local/share/gnome-shell/extensions/gnome-compact-top-bar@metehan-arslan.github.io`.
Increase `height:25` value and reboot/relogin.
```css
#panel, #panel:overview, #panel.unlock-screen, #panel.login-screen, #panel.lock-screen {
  background-color: #000;
  font-weight: 500;
  height: 25px;  // <---- edit this line
  color: #dadada;
  font-feature-settings: "tnum";
  transition-duration: 250ms;
  font-size: 10pt;
  transition: all;
  box-shadow: none;
  transition-duration: 250ms;
}
```

Another option is (i am not sure if this is possible) getting the current taskbar's height and resizing the icons accordingly. You may want to create an issue on App Icons Taskbar repo for this development.
Thanks and sorry for the inconvenience.

Have a great day!
