### ISSUE TITLE
Can i get an option for not having transparent notification? 

### ISSUE THREAD

**Issue by RustLover2910** [metehan-arslan/gnome-compact-top-bar#6]
Its kinda hrad to read the notifications

**Comment by metehan-arslan** [comment]
Hi @RustLover2910! 

You can manually alter, comment-out or remove the related lines starting from 40. The `background-color` property is mainly what you are looking for.

> [~/.local/share/gnome-shell/extensions/compact-top-bar@metehan-arslan.github.io/stylesheet.css](https://github.com/metehan-arslan/gnome-compact-top-bar/blob/main/compact-top-bar%40metehan-arslan.github.io/stylesheet.css#L40)

```CSS
/*Notification Tray*/
.notification-transparency {
  background-color: rgba(0, 0, 0, 0.25);
  font-weight: normal;
  font-feature-settings: "tnum";
  font-size: 11pt;
  transition: all;
  box-shadow: none;
}
```

_**NB:**
GUI Control would be much user friendly, however I do not have enough skills/expertise in JS. I will be leaving this issue open in case someone wants to contribute._
